### ISSUE TITLE
Dynamically add ptd_rebase

### ISSUE THREAD

**Issue by HanselPalencia** [nhs-r-community/NHSRplotthedots#142] opened 2022-02-01 11:26 UTC
From what I've seen it's not possible to dynamically add a `ptd_rebase` function.

For further detail, imagine we have an spc chart that has over five days of consecutively special cases of improvement.
In this case we might want to implement a step change in the spc chart, which we would do with the `ptd_rebase` function, however, the only way to do this is by changing it after having seen the original plot to begin with.

Is there a way to define some rule that says after x number of special causes of improvement/concern implement a step-change to move the mean and upper and lower bounds?

**Comment by ThomUK** [comment] 2022-02-03 18:03
Others may add views here, but I believe that is out of scope for the package as it currently stands.  The main reason being that it's not in line with the methodology trained by the Making Data Count programme.  Ideally before rebasing the reasons for the change should be fairly well understood, to avoid the risk of chasing special cause points up and down the chart.   

There is a paragraph on pp41 of the "getting started" guide on this page that addresses this point:
[https://www.england.nhs.uk/publication/making-data-count/](https://www.england.nhs.uk/publication/making-data-count/)
"What you don’t want to do is automatically 
redraw the chart every time you see a rule 
indicating improvement or decline. You need to 
first question the system, understand the cause 
and then only if, working with others, you’re 
sure there’s a new system, redraw the mean 
and limits from the point the new system was 
introduced. When redrawing don’t forget you 
need a minimum number of data points for 
an informative SPC chart. So if you previously 
decided you needed 20 points to draw a robust 
SPC chart, you will need 20 points from the 
new system to get an equally robust picture"

Of course, that isn't gospel, but is a good starting point.  
It would be possible to do what you want with a two-step process in code.  In the first pass return the dataframe from ptd_spc(), inspect it in code and work out what rebasing to apply, and then in the 2nd step re-run the ptd_spc(), passing in the calculated rebased date to get the chart.

**Comment by ThomUK** [comment] 2022-06-21 19:04
As proposed above, I'm going to close this as out of scope for this package.

The autospc package [https://github.com/HorridTom/autospc](https://github.com/HorridTom/autospc) is actively developed and addresses the need for automatically calculated SPC.  That team did a thorough presentation of the tool to the Making Data Count network meeting, and a video is available on the Making Data Count workspace on NHSFuture.  

It would also be possible to implement the functionality outside of that package by programmatically examining the ptd_spc() dataframe for signals, creating a vector of rebase dates, and then repeating the ptd_spc() call including the calculated rebase dates.  

Happy to re-open this issue for further discussion if needed.

**Closed** 2022-06-21 19:05 UTC
