### ISSUE TITLE
Handling special cause flags with a combination of 2in3 and exceptional points rules

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/NHSRplotthedots#153] opened 2022-07-12 20:16 UTC
![image](https://user-images.githubusercontent.com/10871342/178582366-d5b2b263-260d-471d-bfed-7456bd4606cd.png)
Should the final point here be special cause?
The 3 special cause points here fall outside the control limits.  The final point is showing as common cause even though it is only marginally inside the control limit.  

Should it be special cause (meeting the 2 in 3 points outside the 2nd standard deviation rule)?
Or is classifying it as common cause correct (it is the first point in the 2 to 3 standard deviation range)?

**Comment by ThomUK** [comment] 2022-07-12 20:23
Interesting contrast with this pattern, where the first of the 3 special cause points falls outside the limits.  Same package version.
![image](https://user-images.githubusercontent.com/10871342/178587876-d9fa20a1-f59e-40a5-8046-6cb0981d9c22.png)

**Comment by tomjemmett** [comment] 2023-07-16 13:49
I think in your example you have values that are s>3, s>3, 2<s<3. The first two points are special cause because of being above the UCL (3 sigma), but the last point doesn't trigger the 2 in 3 rule as that is looking explicitly for points between 2 and 3 sigma.

The second example has s>3, 2<s<3, 2<s<3, so in this case the last two points trigger the 2 in 3 rule, and the other point triggers for being above the UCL.

I think that this is the correct logic so marking as closed but feel free to reopen if you disagree!

**Closed by tomjemmett** 2023-07-16 13:49 UTC

**Comment by ThomUK** [comment] 2023-07-17 19:03
I think I was just unlucky to encounter the first configuration.

My thinking was that if 2 in 3 points between 2 and 3 sigma is unusual, then 1 past 3 sigma and 1 between 2 and 3 sigma is more so. I'm combining rule sets in a way that is logical to me, but outside of the established rule.

Happy to close.

**Comment by MatthewCallus** [comment] 2023-07-25 09:17
I can confirm that @tomjemmett is correct. I agree with you though, @ThomUK, that it makes sense to include beyond three-sigma.

The exact logic used in the single chart Excel tool (v4.7) is as follows:

- The point needs to be between two- and three-sigma (not inclusive)
- There needs to be at least two (can be all three) within the run of three meeting the above criterion
- All three points (even if only two meet the above criterion) need to be on the same side of the mean

Because the astronomical point rule requires the point to be beyond three-sigma and the above rule does not include three-sigma, there is a small but non-zero probability of a point lying exactly on three-sigma, which will result in it not triggering either rule. For my SQL query, I included three-sigma in the two- to three-sigma range.

This is how it would look in the Excel tool:

![image](https://github.com/nhs-r-community/NHSRplotthedots/assets/79798278/91964940-55af-44f9-810f-fcd439e14733)
