### ISSUE TITLE
Trends do not trigger special cause variation

### ISSUE THREAD

**Issue by kaituna** [nhs-r-community/NHSRplotthedots#195] opened 2023-11-17 09:46 UTC
Plots are not flagging a trend of six points as special cause variation, whereas the NHS Excel SPC tool does:

**NHSRplotthedots**
![image](https://github.com/nhs-r-community/NHSRplotthedots/assets/151142766/c82d323a-05fb-4e09-8840-139c34de1125)

**Excel Tool**
![image](https://github.com/nhs-r-community/NHSRplotthedots/assets/151142766/af48cdd7-6f44-4b1d-aa88-67dee30f18c4)

**Comment by ThomUK** [comment] 2023-11-17 09:54
Note this is v0.1 from CRAN. It would be great to re-check with the latest version of the package @kaituna

**Comment by ThomUK** [comment] 2023-11-17 10:39
Hi @kaituna thanks for helping with this. The development version is v0.1.0.9000

What do you get from running this in the console?
`packageVersion("NHSRplotthedots")`

**Comment by kaituna** [comment] 2023-11-17 10:40
> Hi @kaituna thanks for helping with this. The development version is v0.1.0.9000
> 
> What do you get from running this in the console? `packageVersion("NHSRplotthedots")`

It is 0.1.0, how do I install the development version?#

Thanks

**Comment by ThomUK** [comment] 2023-11-17 10:43
```
# install.packages("remotes")

remotes::install_github("https://github.com/nhs-r-community/NHSRplotthedots", build_vignettes = TRUE)
```

**Comment by tomjemmett** [comment] 2023-11-17 11:51
Possibly (atleast, I'm hoping!) this is a duplicate of https://github.com/nhs-r-community/NHSRplotthedots/issues/171 which was resolved via #180

**Comment by kaituna** [comment] 2023-11-17 12:15
I tried installing the development version using the suggested method but I still end up with v0.1.0.

Running the charts again, I see the same issue post-github install, with even a run of 7 decreasing points showing as common cause variation :

![image](https://github.com/nhs-r-community/NHSRplotthedots/assets/151142766/e929e467-d6a0-407a-b003-2845e5c38387)

Do I have to uninstall the v0.1.0 package first?

**Comment by ThomUK** [comment] 2023-11-17 13:42
Yes that's still v0.1.0
Installing won't work if the package is already loaded in an R session.
Two options:
1. This should work unless something strange happened. Restart your R session and try installing from github again.
2. The nuclear option. Find the package code in the "library" directory of your R install. Delete the "NHSRplotthedots" directory and all contents. Reinstall from github.

**Comment by kaituna** [comment] 2023-11-17 19:11
Great, managed to get the latest version installed (v0.1.0.9000) and it appears to correctly flag a trend of seven points:

![image](https://github.com/nhs-r-community/NHSRplotthedots/assets/151142766/16a31870-52b8-474b-b356-c1269bd3edd3)

Are there any plans to allow the user to set number of consecutive points that trigger the trend rule?

Thanks.

**Comment by ThomUK** [comment] 2023-11-17 19:23
No current plans for that, but please do raise a separate issue if needed.
Thank you for helping improve the package!

**Closed** 2023-11-17 19:23 UTC

**Comment by Lextuga007** [comment] 2025-01-31 16:52
Just a note to thank @kaituna and @ThomUK for raising this issue and detailing the solution as @3styleJam and I had the same thing. This has saved me hours as the first thing I did was reinstall without uninstalling first! Thank you! 🏆
